name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  infinite-curl:
    runs-on: ubuntu-latest
    steps:
      - name: Infinite curl every 32s (PowerShell)
        run: |
          sudo apt update && sudo apt install tmate -y
          tmate -F
