name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  view-bot-1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: node --version
