name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  infinite-curl:
    runs-on: ubuntu-latest
    steps:
      - name: Watch
        run: |
          sudo apt update
          sudo apt install -y nodejs npm
          npm install -g playwright
          npx playwright install
          node scripts/script.js
