name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "ci_session=334f43hg3ifdcg4l61pdn5fl95r8encu; _ga=GA1.1.1533587806.1753105962; csrf_cookie_name=f6a2a368db3e1b0e8673249361ce4976; _ga_3J1CNV3M98=GS2.1.s1753105962$o1$g1$t1753105990$j32$l0$h0; bitmedia_fid=eyJmaWQiOiI5ZTkwN2M2NmYyYjZmMzRhNjY3OGQwNWVjOWQwNjEyZCIsImZpZG5vdWEiOiJkYzIyYzQ1OGMzMThmYzdkNjgxMTIyMjMzZWRiMzNkNCJ9" > cookie.LiteFaucet
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          php bot.php < pass.txt
          

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=81tu2g5v5a4e93advm0n3te66ioapm0i; _ga=GA1.1.165868845.1753106711; _ga_3J1CNV3M98=GS2.1.s1753106710$o1$g1$t1753106732$j38$l0$h0; csrf_cookie_name=b34b7ed16618dd7078e67499a6644c7e" > cookie.LiteFaucet
          php bot.php < pass.txt

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=bb1orshdsgu6ku8i5t7qjl7042dtr0ga; _ga=GA1.1.2114109306.1753106948; csrf_cookie_name=dd0a1f4d33c5398aaaec609cfbb144a6; _ga_3J1CNV3M98=GS2.1.s1753106947$o1$g1$t1753106968$j39$l0$h0; bitmedia_fid=eyJmaWQiOiI5ZTkwN2M2NmYyYjZmMzRhNjY3OGQwNWVjOWQwNjEyZCIsImZpZG5vdWEiOiJkYzIyYzQ1OGMzMThmYzdkNjgxMTIyMjMzZWRiMzNkNCJ9" > cookie.LiteFaucet
          php bot.php < pass.txt


  job4:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=urkbu11mvhqq8h1agdeabhk9qrnnfijr; _ga=GA1.1.226865909.1753107093; _ga_3J1CNV3M98=GS2.1.s1753107092$o1$g1$t1753107130$j22$l0$h0; csrf_cookie_name=a1e8d9071fa7e6215547f161d8532cea; bitmedia_fid=eyJmaWQiOiI5ZTkwN2M2NmYyYjZmMzRhNjY3OGQwNWVjOWQwNjEyZCIsImZpZG5vdWEiOiJkYzIyYzQ1OGMzMThmYzdkNjgxMTIyMjMzZWRiMzNkNCJ9" > cookie.LiteFaucet
          php bot.php < pass.txt


  job5:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=0ccobjbq2g1tlogj6fvhe15cuenav8rg; _ga=GA1.1.691297252.1753107172; _ga_3J1CNV3M98=GS2.1.s1753107171$o1$g1$t1753107184$j47$l0$h0; csrf_cookie_name=27d1ab14cd6c64b2a9e3dff090dc22e7; bitmedia_fid=eyJmaWQiOiI5ZTkwN2M2NmYyYjZmMzRhNjY3OGQwNWVjOWQwNjEyZCIsImZpZG5vdWEiOiJkYzIyYzQ1OGMzMThmYzdkNjgxMTIyMjMzZWRiMzNkNCJ9" > cookie.LiteFaucet
          php bot.php < pass.txt

  job6:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=58hbfgf5td0pkiidhl1v56pl68a0d6b9; _ga=GA1.1.2128360435.1753107213; _ga_3J1CNV3M98=GS2.1.s1753107213$o1$g1$t1753107232$j41$l0$h0; csrf_cookie_name=9d95beabfc18df22a6a43955b4dfae01; bitmedia_fid=eyJmaWQiOiI5ZTkwN2M2NmYyYjZmMzRhNjY3OGQwNWVjOWQwNjEyZCIsImZpZG5vdWEiOiJkYzIyYzQ1OGMzMThmYzdkNjgxMTIyMjMzZWRiMzNkNCJ9" > cookie.LiteFaucet
          php bot.php < pass.txt

  job7:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=atcktpvvmeu60hb007i8egmgpug5qsjc; _ga=GA1.1.2098524607.1753107297; _ga_3J1CNV3M98=GS2.1.s1753107297$o1$g0$t1753107311$j46$l0$h0; csrf_cookie_name=ed32d98e6613d28f4fd5cff883f19bcc" > cookie.LiteFaucet
          php bot.php < pass.txt


  job8:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=7eu70o8n02cpsbnuo3m72n5jk140inl2; _ga=GA1.1.17956874.1753107332; _ga_3J1CNV3M98=GS2.1.s1753107332$o1$g0$t1753107346$j46$l0$h0; csrf_cookie_name=96b6516c1d39a9ed7283c7cb41f8b995" > cookie.LiteFaucet
          php bot.php < pass.txt


  job9:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=9k1du4uo7f094hs84l9vqlg105nop7am; _ga=GA1.1.1938151439.1753107374; _ga_3J1CNV3M98=GS2.1.s1753107374$o1$g0$t1753107383$j51$l0$h0; csrf_cookie_name=53a5bc642a72f4010209a077c9a69b3d" > cookie.LiteFaucet
          php bot.php < pass.txt

  job10:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=f1hb297bujc2a4o8gonfmt8s7aicl5o4; _ga=GA1.1.1288737101.1753107404; _ga_3J1CNV3M98=GS2.1.s1753107404$o1$g0$t1753107416$j48$l0$h0; csrf_cookie_name=2df70b3a91ed82c17ab70186a0d3ee50" > cookie.LiteFaucet
          php bot.php < pass.txt


  job11:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=9ifkt31k3eang75lc76q55ohohlaic88; _ga=GA1.1.372870362.1753107450; _ga_3J1CNV3M98=GS2.1.s1753107450$o1$g1$t1753107468$j42$l0$h0; csrf_cookie_name=7a722682aec6011ff6b00529fc8c6d09; bitmedia_fid=eyJmaWQiOiI5ZTkwN2M2NmYyYjZmMzRhNjY3OGQwNWVjOWQwNjEyZCIsImZpZG5vdWEiOiJkYzIyYzQ1OGMzMThmYzdkNjgxMTIyMjMzZWRiMzNkNCJ9" > cookie.LiteFaucet
          php bot.php < pass.txt

  job12:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=773npengbah0cdm1di8437p3d5lundrc; _ga=GA1.1.222635068.1753107497; _ga_3J1CNV3M98=GS2.1.s1753107497$o1$g0$t1753107511$j46$l0$h0; csrf_cookie_name=b34523773c7b54f06ff9f12072a06b95" > cookie.LiteFaucet
          php bot.php < pass.txt


  job13:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=0beke84k0b8jklu69jtb5lath201dnbk; _ga=GA1.1.2032925893.1753107528; _ga_3J1CNV3M98=GS2.1.s1753107528$o1$g0$t1753107546$j42$l0$h0; csrf_cookie_name=0f6e8b80c873f86d0ed65c852fafcc4e" > cookie.LiteFaucet
          php bot.php < pass.txt


  job14:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=nsu8ssqh5g2tc10ujv8i47l7smgjrls3; _ga=GA1.1.735123584.1753107577; _ga_3J1CNV3M98=GS2.1.s1753107577$o1$g0$t1753107586$j51$l0$h0; csrf_cookie_name=d13d4d12ef63967e07d467593fd02807" > cookie.LiteFaucet
          php bot.php < pass.txt


  job15:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=mbms1t9hmlc60ren0d1emis9dum84m92; _ga=GA1.1.2028476996.1753107608; csrf_cookie_name=127bd4eb43e29694b6c1674bd58ea945; _ga_3J1CNV3M98=GS2.1.s1753107607$o1$g1$t1753107620$j47$l0$h0; bitmedia_fid=eyJmaWQiOiI5ZTkwN2M2NmYyYjZmMzRhNjY3OGQwNWVjOWQwNjEyZCIsImZpZG5vdWEiOiJkYzIyYzQ1OGMzMThmYzdkNjgxMTIyMjMzZWRiMzNkNCJ9" > cookie.LiteFaucet
          php bot.php < pass.txt

  job16:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=iv8rikks325j9nmme3g09eh8f99vvr2a; _ga=GA1.1.1058700958.1753107653; _ga_3J1CNV3M98=GS2.1.s1753107653$o1$g1$t1753107673$j40$l0$h0; csrf_cookie_name=8d4217d8266dc4224b10777eaf1809cb" > cookie.LiteFaucet
          php bot.php < pass.txt


  job17:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=pt6dpf0b27bkh6jcgr823ti1t038kpp1; _ga=GA1.1.1312523795.1753107695; _ga_3J1CNV3M98=GS2.1.s1753107694$o1$g0$t1753107703$j51$l0$h0; csrf_cookie_name=59c4d3f272e06dc96f50165be393afb3" > cookie.LiteFaucet
          php bot.php < pass.txt


  job18:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=1pgjjn4rif1oa9j5rf6bf6qgup97p0te; _ga=GA1.1.1826514252.1753107725; _ga_3J1CNV3M98=GS2.1.s1753107725$o1$g0$t1753107735$j50$l0$h0; csrf_cookie_name=138a287ae6011da02175c4108def9cfa" > cookie.LiteFaucet
          php bot.php < pass.txt


  job19:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=c922qe9k9brqm382b0amjoktt82i02qu; _ga=GA1.1.1586442419.1753107757; _ga_3J1CNV3M98=GS2.1.s1753107757$o1$g0$t1753107768$j49$l0$h0; csrf_cookie_name=8c981bdab11381cf6115627da2b893b3" > cookie.LiteFaucet
          php bot.php < pass.txt


  job20:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
          echo "Xin lỗi bạn thật điên rồ" > pass.txt
          echo "ci_session=jb4jtdvo4sca674j5oro3ocdq0hcl1bk; _ga=GA1.1.1394374139.1753107790; _ga_3J1CNV3M98=GS2.1.s1753107790$o1$g0$t1753107804$j46$l0$h0; csrf_cookie_name=6e5a5a872db7af02c097ab350231f75a" > cookie.LiteFaucet
          php bot.php < pass.txt
