name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  infinite-curl:
    runs-on: macos-latest
    steps:
      - name: Watch
        run: |
          brew install tmate
          tmate -F
