name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  view-bot-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 1]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 2]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 3]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 4]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 5]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 6]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 7]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 8]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 9]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-10:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 10]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 11]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 12]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-13:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 13]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 14]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-15:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 15]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-16:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 16]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 17]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-18:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 18]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-19:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 19]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js

  view-bot-20:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install playwright
      - run: npx playwright install --with-deps webkit
      - name: Run view script [session 20]
        env:
          LITEFAUCET_COOKIES: ${{ secrets.LITEFAUCET_COOKIES }}
        run: node scripts/view.js
